language: rust
rust: stable
dist: xenial

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=clang++; fi

script:
  - cargo test --verbose
  - cargo test --verbose --features egl  # Doesnâ€™t do anything, but should still build
